version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    
    environment:
      POSTGRES_DB: "academy"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"